const { SlashCommandBuilder } = require('@discordjs/builders');
const { Client, MessageEmbed } = require('discord.js');
const wait = require('node:timers/promises').setTimeout;
const chalk = require('chalk')

module.exports = {
    data: new SlashCommandBuilder()
	.setName('screenshot')
	.setDescription('Sends the screenshot reminder embed'),

    async execute(interaction) {
		console.log(chalk.blue(`${interaction.user.tag} used the command: /screenshot`))

        const userembed = new MessageEmbed()
            .setTitle("/screenshot")
            .setFooter({text: "Generated by " + interaction.client.user.tag })
            .setDescription(`
Hey, instead of waiting for a staff member to verify your screenshot, did you know that you can use the **/rank** command instead?

The syntax is pretty simple

**/rank <valorant username> <all characters after the hashtag>**

Just make sure you do not include the hashtag in the second argument!
            `)
            .setColor(0xF44F52)
            .setTimestamp()

            await interaction.reply({ embeds: [userembed] })

       },
}

