const { SlashCommandBuilder } = require('@discordjs/builders');
const { Client, MessageEmbed } = require('discord.js');
const wait = require('node:timers/promises').setTimeout;
const chalk = require('chalk')

module.exports = {
    data: new SlashCommandBuilder()
	.setName('waystoverify')
	.setDescription('All the different ways to verify your rank')
    .addStringOption(option => option.setName('method').setDescription('The method to verify')
		.addChoice('Screenshot', 'screenshot')
		.addChoice('Rank Command', '/rank')),

    async execute(interaction) {
	console.log(chalk.blue(`${interaction.user.tag} used the command: /waystoverify`))
	const method = interaction.options.getString('method');

    const screenshotembed = new MessageEmbed()
    .setTitle("Screenshot Verification")
    .setFooter({text: "Generated by " + interaction.client.user.tag })
    .setDescription(`
To verify your rank with a screenshot, please: 
    <:dash:969131036921434142> Provide a photo of with you in a competitive lobby.
    <:dash:969131036921434142> Provide the words \`NerdPunt - <Current Date>\` in the chat box.
    <:dash:969131036921434142> Make sure the image is **not** cropped
    <:dash:969131036921434142> Make sure both your ingame rank and username are visible and unedited.
    <:dash:969131036921434142> If a staff member asks you to send them a friend request, failure will result in your role being stripped from you.

    <:dash:969131036921434142> **DO NOT PING STAFF MEMBERS**, if you don't want to wait, read \`/waystoverify Rank Command\`
    `)
    .setColor(0xF44F52)
    .setTimestamp()

    const rankcommandembed = new MessageEmbed()
    .setTitle("Rank Command Verification")
    .setFooter({text: "Generated by " + interaction.client.user.tag })
    .setDescription(`
The rank command is the preferred way of verification, as it automates the verification system.

You can use the command \`/rank <Valorant username> <characters after the hashtag>\`. You must ensure you are **not** including the hashtag.
    `)
    .setColor(0xF44F52)
    .setTimestamp()

    const generalembed = new MessageEmbed()
    .setTitle("Ways to verify")
    .setFooter({text: "Generated by " + interaction.client.user.tag })
    .setDescription(`
There are 2 ways you can verify, one with manual verification and one with automatic. For the sake of our staff, we prefer the automatic method, but either is fine.

The automatic method is utilising the command \`/rank\`. You can get more information on the correct syntax of this command with the command \`/waystoverify Rank Command\`

The alternative way to verify is by sending a screenshot, but there are strict rules around what screenshots will be accepted/denied. Use the command \`/waystoverify Screenshot\` to see these rules.
    `)
    .setColor(0xF44F52)
    .setTimestamp()

	if (method == 'screenshot') {return await interaction.reply({ embeds: [screenshotembed] })}
    if (method == '/rank') {return await interaction.reply({ embeds: [rankcommandembed] })}
    if (!method) {return await interaction.reply({ embeds: [generalembed] })}
    },
}