const { SlashCommandBuilder } = require('@discordjs/builders');
const { Client, MessageEmbed } = require('discord.js');
const wait = require('node:timers/promises').setTimeout;
const chalk = require('chalk')

module.exports = {
    data: new SlashCommandBuilder()
	.setName('avatar')
	.setDescription('Gets the avatar of a user!')
	.addUserOption(option =>
		option.setName('user')
			.setDescription('The user to lookup')),

    async execute(interaction) {
        console.log(chalk.blue(`${interaction.user.tag} used the command: /avatar`))


    const User = interaction.options.getUser('user') ?? interaction.user

    const userembed = new MessageEmbed()
    .setTitle("User Lookup")
    .setFooter({text: "Generated by " + interaction.client.user.tag })
    .setColor('DARK_BUT_NOT_BLACK')
    .setTimestamp()
    .setImage(User.displayAvatarURL() + "?size=2048");

    await interaction.reply({ embeds: [userembed] });
    },
}